services:
  api:
    build: .
    ports:
      - "4000:8000"
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=yash
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=yash
      - SECRET_KEY=4ee67ca6a7e5c108ea6964c22897a0fc497b8c800c207c82588a4d3f82c29223
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=yash
      - POSTGRES_PASSWORD=yash
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql

volumes:
  postgres-db: