@host = http://127.0.0.1:8000
@token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE3ODYwODQ1NjJ9.qrB5V3Y6wpRuli2VeDvrvsvxmdF6-wWK_ZWXaOMO6vI"

GET {{host}}/

###
DELETE {{host}}/posts/1


###
POST {{host}}/login
Content-Type: application/x-www-form-urlencoded

username=yash@example.com&password=mummyily

###
POST {{host}}/login
Content-Type: application/x-www-form-urlencoded

username=yash@example.com&password=mummyily

###
POST {{host}}/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE3ODYwODkyODN9.LEvaCr9s5sFOSW6DlMpqC5EbqGazbTP2cZ6CKIbzsLo

{
  "title": "maa",
  "content": "mummyily"
}
